package com.lab.app.ketman.mybatis.domain;

public class UserMst {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_mst.id
	 * @mbg.generated  Sun Dec 27 16:36:32 JST 2020
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_mst.sex
	 * @mbg.generated  Sun Dec 27 16:36:32 JST 2020
	 */
	private Integer sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_mst.tel
	 * @mbg.generated  Sun Dec 27 16:36:32 JST 2020
	 */
	private Long tel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_mst.postal_code
	 * @mbg.generated  Sun Dec 27 16:36:32 JST 2020
	 */
	private Integer postal_code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_mst.age
	 * @mbg.generated  Sun Dec 27 16:36:32 JST 2020
	 */
	private Integer age;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_mst.id
	 * @return  the value of user_mst.id
	 * @mbg.generated  Sun Dec 27 16:36:32 JST 2020
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_mst.id
	 * @param id  the value for user_mst.id
	 * @mbg.generated  Sun Dec 27 16:36:32 JST 2020
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_mst.sex
	 * @return  the value of user_mst.sex
	 * @mbg.generated  Sun Dec 27 16:36:32 JST 2020
	 */
	public Integer getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_mst.sex
	 * @param sex  the value for user_mst.sex
	 * @mbg.generated  Sun Dec 27 16:36:32 JST 2020
	 */
	public void setSex(Integer sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_mst.tel
	 * @return  the value of user_mst.tel
	 * @mbg.generated  Sun Dec 27 16:36:32 JST 2020
	 */
	public Long getTel() {
		return tel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_mst.tel
	 * @param tel  the value for user_mst.tel
	 * @mbg.generated  Sun Dec 27 16:36:32 JST 2020
	 */
	public void setTel(Long tel) {
		this.tel = tel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_mst.postal_code
	 * @return  the value of user_mst.postal_code
	 * @mbg.generated  Sun Dec 27 16:36:32 JST 2020
	 */
	public Integer getPostal_code() {
		return postal_code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_mst.postal_code
	 * @param postal_code  the value for user_mst.postal_code
	 * @mbg.generated  Sun Dec 27 16:36:32 JST 2020
	 */
	public void setPostal_code(Integer postal_code) {
		this.postal_code = postal_code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_mst.age
	 * @return  the value of user_mst.age
	 * @mbg.generated  Sun Dec 27 16:36:32 JST 2020
	 */
	public Integer getAge() {
		return age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_mst.age
	 * @param age  the value for user_mst.age
	 * @mbg.generated  Sun Dec 27 16:36:32 JST 2020
	 */
	public void setAge(Integer age) {
		this.age = age;
	}

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_mst.tel
     *
     * @mbg.generated Thu Dec 10 21:40:34 JST 2020
     */
    //private Integer tel;

    

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_mst.tel
     *
     * @return the value of user_mst.tel
     *
     * @mbg.generated Thu Dec 10 21:40:34 JST 2020
     */
	/*
	 * public Integer getTel() { return tel; }
	 */

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_mst.tel
     *
     * @param tel the value for user_mst.tel
     *
     * @mbg.generated Thu Dec 10 21:40:34 JST 2020
     */
	/*
	 * public void setTel(Integer tel) { this.tel = tel; }
	 */

    
}