package com.lab.app.ketman.mybatis.domain;

public class UserMstWithBLOBs extends UserMst {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_mst.user_name
	 * @mbg.generated  Sun Dec 27 16:36:32 JST 2020
	 */
	private String user_name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_mst.user_name_kana
	 * @mbg.generated  Sun Dec 27 16:36:32 JST 2020
	 */
	private String user_name_kana;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_mst.addr1
	 * @mbg.generated  Sun Dec 27 16:36:32 JST 2020
	 */
	private String addr1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_mst.addr2
	 * @mbg.generated  Sun Dec 27 16:36:32 JST 2020
	 */
	private String addr2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_mst.addr3
	 * @mbg.generated  Sun Dec 27 16:36:32 JST 2020
	 */
	private String addr3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_mst.addr4
	 * @mbg.generated  Sun Dec 27 16:36:32 JST 2020
	 */
	private String addr4;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_mst.addr5
	 * @mbg.generated  Sun Dec 27 16:36:32 JST 2020
	 */
	private String addr5;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_mst.birth_date
	 * @mbg.generated  Sun Dec 27 16:36:32 JST 2020
	 */
	private String birth_date;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_mst.user_name
	 * @return  the value of user_mst.user_name
	 * @mbg.generated  Sun Dec 27 16:36:32 JST 2020
	 */
	public String getUser_name() {
		return user_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_mst.user_name
	 * @param user_name  the value for user_mst.user_name
	 * @mbg.generated  Sun Dec 27 16:36:32 JST 2020
	 */
	public void setUser_name(String user_name) {
		this.user_name = user_name == null ? null : user_name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_mst.user_name_kana
	 * @return  the value of user_mst.user_name_kana
	 * @mbg.generated  Sun Dec 27 16:36:32 JST 2020
	 */
	public String getUser_name_kana() {
		return user_name_kana;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_mst.user_name_kana
	 * @param user_name_kana  the value for user_mst.user_name_kana
	 * @mbg.generated  Sun Dec 27 16:36:32 JST 2020
	 */
	public void setUser_name_kana(String user_name_kana) {
		this.user_name_kana = user_name_kana == null ? null : user_name_kana.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_mst.addr1
	 * @return  the value of user_mst.addr1
	 * @mbg.generated  Sun Dec 27 16:36:32 JST 2020
	 */
	public String getAddr1() {
		return addr1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_mst.addr1
	 * @param addr1  the value for user_mst.addr1
	 * @mbg.generated  Sun Dec 27 16:36:32 JST 2020
	 */
	public void setAddr1(String addr1) {
		this.addr1 = addr1 == null ? null : addr1.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_mst.addr2
	 * @return  the value of user_mst.addr2
	 * @mbg.generated  Sun Dec 27 16:36:32 JST 2020
	 */
	public String getAddr2() {
		return addr2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_mst.addr2
	 * @param addr2  the value for user_mst.addr2
	 * @mbg.generated  Sun Dec 27 16:36:32 JST 2020
	 */
	public void setAddr2(String addr2) {
		this.addr2 = addr2 == null ? null : addr2.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_mst.addr3
	 * @return  the value of user_mst.addr3
	 * @mbg.generated  Sun Dec 27 16:36:32 JST 2020
	 */
	public String getAddr3() {
		return addr3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_mst.addr3
	 * @param addr3  the value for user_mst.addr3
	 * @mbg.generated  Sun Dec 27 16:36:32 JST 2020
	 */
	public void setAddr3(String addr3) {
		this.addr3 = addr3 == null ? null : addr3.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_mst.addr4
	 * @return  the value of user_mst.addr4
	 * @mbg.generated  Sun Dec 27 16:36:32 JST 2020
	 */
	public String getAddr4() {
		return addr4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_mst.addr4
	 * @param addr4  the value for user_mst.addr4
	 * @mbg.generated  Sun Dec 27 16:36:32 JST 2020
	 */
	public void setAddr4(String addr4) {
		this.addr4 = addr4 == null ? null : addr4.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_mst.addr5
	 * @return  the value of user_mst.addr5
	 * @mbg.generated  Sun Dec 27 16:36:32 JST 2020
	 */
	public String getAddr5() {
		return addr5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_mst.addr5
	 * @param addr5  the value for user_mst.addr5
	 * @mbg.generated  Sun Dec 27 16:36:32 JST 2020
	 */
	public void setAddr5(String addr5) {
		this.addr5 = addr5 == null ? null : addr5.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_mst.birth_date
	 * @return  the value of user_mst.birth_date
	 * @mbg.generated  Sun Dec 27 16:36:32 JST 2020
	 */
	public String getBirth_date() {
		return birth_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_mst.birth_date
	 * @param birth_date  the value for user_mst.birth_date
	 * @mbg.generated  Sun Dec 27 16:36:32 JST 2020
	 */
	public void setBirth_date(String birth_date) {
		this.birth_date = birth_date == null ? null : birth_date.trim();
	}

	/*
	 * private String tel;
	 * 
	 * public Long getTel() { return tel; }
	 */
}